# Generated by Django 6.1.1 on 2026-09-03 08:58

import apps.projects.models
import apps.taxonomy.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '0001_initial'),
        ('taxonomy', '0002_seed_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('government', 'Government'), ('personal', 'Personal (community)')], db_index=True, max_length=12)),
                ('title_en', apps.taxonomy.fields.NFCCharField(max_length=200)),
                ('title_ne', apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=200)),
                ('slug', apps.taxonomy.fields.NFCSlugField(allow_unicode=True, max_length=220, unique=True)),
                ('problem_statement', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('target_users', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('expected_outcome', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('success_indicators', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('summary_en', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('summary_ne', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('description_md', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('background', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('current_state', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('limitations', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('related_initiatives', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=15)),
                ('experience_band', models.CharField(blank=True, default='', max_length=30)),
                ('estimated_effort', models.CharField(blank=True, choices=[('small', 'Small (about 1 week)'), ('medium', 'Medium (1-4 weeks)'), ('large', 'Large (over 4 weeks)')], default='', max_length=10)),
                ('contributor_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=True)),
                ('location', apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=120)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('contribution_mode', models.CharField(blank=True, choices=[('open_direct', 'Open direct contribution'), ('application', 'Application required'), ('hybrid', 'Hybrid (open tasks and application workstreams)')], default='', max_length=15)),
                ('prerequisites', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('communication_channel', models.URLField(blank=True, default='')),
                ('response_sla', models.CharField(blank=True, choices=[('24h', 'Within 24 hours'), ('3d', 'Within 3 days'), ('1w', 'Within 1 week')], default='1w', max_length=3)),
                ('code_of_conduct_url', models.URLField(blank=True, default='')),
                ('repository_url', models.URLField(blank=True, default='')),
                ('default_branch', apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=100)),
                ('issue_tracker_url', models.URLField(blank=True, default='')),
                ('documentation_url', models.URLField(blank=True, default='')),
                ('architecture_url', models.URLField(blank=True, default='')),
                ('environments_url', models.URLField(blank=True, default='')),
                ('test_build_instructions', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('ci_status_url', models.URLField(blank=True, default='')),
                ('governance_model', models.CharField(blank=True, choices=[('maintainer_consensus', 'Maintainer consensus'), ('lead_maintainer', 'Lead maintainer decides'), ('ministry_approval', 'Ministry approval required')], default='', max_length=25)),
                ('outcome_ownership', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('escalation_path', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('completion_criteria', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('signoff_model', models.CharField(blank=True, choices=[('dco', 'DCO-style sign-off'), ('cla', 'CLA required'), ('none', 'None required (non-code)')], default='', max_length=15)),
                ('third_party_rights_confirmed', models.BooleanField(default=False)),
                ('content_license', apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=200)),
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential')], default='public', max_length=12)),
                ('security_contact', models.EmailField(blank=True, default='', max_length=254)),
                ('vulnerability_disclosure_url', models.URLField(blank=True, default='')),
                ('prohibited_data_statement', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved / scheduled'), ('open_for_contribution', 'Open for contribution'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='draft', max_length=25)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_publication_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('dependencies', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('risks', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('last_maintainer_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=120)),
                ('ownership_verification', models.CharField(choices=[('unverified', 'Unverified'), ('verified_github', 'Verified via GitHub'), ('verified_domain', 'Verified via domain'), ('verified_manual', 'Verified manually by Super Admin')], default='unverified', max_length=20)),
                ('outcome_summary', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('impact_summary', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('lessons_learned', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('archive_reason', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('contribution_types', models.ManyToManyField(blank=True, related_name='projects', to='taxonomy.taxonomyterm')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='taxonomy.approvedlicense')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='ministries.ministryorganization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='projects', to='taxonomy.skill')),
                ('technologies', models.ManyToManyField(blank=True, related_name='technology_projects', to='taxonomy.taxonomyterm')),
            ],
            options={
                'ordering': ['-status_changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('interest', 'Expressed interest'), ('application', 'Application'), ('assignment', 'Assigned work')], default='application', max_length=12)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('info_requested', 'Information requested'), ('waitlisted', 'Waitlisted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=15)),
                ('motivation', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('screening_answers', models.JSONField(blank=True, default=list)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_applications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='projects.project')),
            ],
            options={
                'verbose_name': 'application',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('proposal', 'Proposal'), ('requirements', 'Requirements'), ('architecture', 'Architecture'), ('design', 'Design'), ('api_doc', 'API documentation'), ('research', 'Research'), ('terms', 'Terms'), ('image', 'Image'), ('other', 'Other')], max_length=12)),
                ('file', models.FileField(max_length=255, upload_to=apps.projects.models.attachment_upload_path)),
                ('original_filename', apps.taxonomy.fields.NFCCharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=2)),
                ('classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential')], default='public', max_length=12)),
                ('scan', models.CharField(choices=[('pending', 'Pending scan'), ('clean', 'Clean'), ('quarantined', 'Quarantined'), ('failed', 'Scan failed')], db_index=True, default='pending', max_length=12)),
                ('accessibility_note', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_change', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('repository', 'Repository'), ('demo', 'Demo'), ('website', 'Website'), ('documentation', 'Documentation'), ('article', 'Article'), ('other', 'Other')], max_length=15)),
                ('url', models.URLField()),
                ('label', apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project')),
            ],
            options={
                'ordering': ['kind', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead maintainer'), ('maintainer', 'Maintainer'), ('reviewer', 'Reviewer')], default='maintainer', max_length=12)),
                ('can_review_merge', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintainer_assignments', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintainer_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'user__username'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='maintainers',
            field=models.ManyToManyField(related_name='maintained_projects', through='projects.ProjectMaintainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', apps.taxonomy.fields.NFCCharField(max_length=200)),
                ('description', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('achieved', 'Achieved'), ('dropped', 'Dropped')], default='planned', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', apps.taxonomy.fields.NFCCharField(max_length=300)),
                ('help_text', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_questions', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSuitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suitability_completed', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suitability_confirmed', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suitability', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', apps.taxonomy.fields.NFCCharField(max_length=200)),
                ('description', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('is_starter', models.BooleanField(default=False)),
                ('issue_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('skills', models.ManyToManyField(blank=True, related_name='tasks', to='taxonomy.skill')),
            ],
            options={
                'ordering': ['status', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', apps.taxonomy.fields.NFCCharField(max_length=200)),
                ('body', apps.taxonomy.fields.NFCTextField()),
                ('kind', models.CharField(choices=[('progress', 'Progress'), ('milestone', 'Milestone'), ('release', 'Release/result'), ('completion', 'Completion summary')], default='progress', max_length=12)),
                ('link', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_updates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='projects.project')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_versions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project version',
                'ordering': ['project', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('published', 'Published'), ('revoked', 'Approval revoked'), ('restored', 'Restored from archive')], db_index=True, max_length=20)),
                ('comment', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('from_status', models.CharField(blank=True, default='', max_length=25)),
                ('to_status', models.CharField(blank=True, default='', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='projects.project')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_reviews', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='projects.projectversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.projectversion'),
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('submitted', 'Submitted'), ('status_changed', 'Status changed'), ('info_requested', 'Information requested'), ('info_provided', 'Information provided'), ('commented', 'Comment'), ('assigned', 'Work assigned'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('comment', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('from_status', models.CharField(blank=True, default='', max_length=15)),
                ('to_status', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.application')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['application', 'created_at'], name='idx_appevent_app_created')],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='idx_app_applicant_status'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['project', 'status'], name='idx_application_project_status'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('project', 'applicant', 'kind'), name='uniq_application_project_applicant_kind'),
        ),
        migrations.AddIndex(
            model_name='projectattachment',
            index=models.Index(fields=['project', 'kind'], name='idx_attachment_project_kind'),
        ),
        migrations.AddConstraint(
            model_name='projectbookmark',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='uniq_bookmark_user_project'),
        ),
        migrations.AddConstraint(
            model_name='projectlink',
            constraint=models.UniqueConstraint(fields=('project', 'url'), name='uniq_project_link_url'),
        ),
        migrations.AddConstraint(
            model_name='projectmaintainer',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uniq_project_maintainer'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['project', 'status'], name='idx_milestone_project_status'),
        ),
        migrations.AddIndex(
            model_name='projectscreeningquestion',
            index=models.Index(fields=['project'], name='idx_screening_project'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'status'], name='idx_task_project_status'),
        ),
        migrations.AddIndex(
            model_name='projectupdate',
            index=models.Index(fields=['project', '-created_at'], name='idx_update_project_created'),
        ),
        migrations.AddIndex(
            model_name='projectversion',
            index=models.Index(fields=['project', '-submitted_at'], name='idx_version_project_submitted'),
        ),
        migrations.AddConstraint(
            model_name='projectversion',
            constraint=models.UniqueConstraint(fields=('project', 'version_number'), name='uniq_project_version_number'),
        ),
        migrations.AddIndex(
            model_name='projectreview',
            index=models.Index(fields=['project', '-created_at'], name='idx_review_project_created'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type', 'status'], name='idx_project_type_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['ministry', 'status'], name='idx_project_ministry_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-published_at'], name='idx_project_status_published'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['deadline'], name='idx_project_deadline'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ministry__isnull', False), ('project_type', 'government')), models.Q(('ministry__isnull', True), ('project_type', 'personal')), _connector='OR'), name='chk_project_type_ministry'),
        ),
    ]
