# Generated by Django 6.1.1 on 2026-09-03 18:54

import apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlink',
            name='url',
            field=apps.accounts.fields.NormalizedURLField(),
        ),
    ]
