# Generated by Django 6.1.1 on 2026-09-04 19:52

import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectlink_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', apps.taxonomy.fields.NFCCharField(max_length=30)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_terms_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'community terms acceptance',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'version'], name='idx_terms_user_version')],
                'constraints': [models.UniqueConstraint(fields=('user', 'version'), name='uniq_terms_user_version')],
            },
        ),
    ]
