# Generated by Django 6.1.1 on 2026-09-03 08:38

import apps.accounts.fields
import apps.accounts.models
import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('taxonomy', '0002_seed_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', apps.taxonomy.fields.NFCCharField(max_length=200)),
                ('credential', apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=200)),
                ('field_of_study', apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=120)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_year'],
                'indexes': [models.Index(fields=['user'], name='idx_memberedu_user')],
            },
        ),
        migrations.CreateModel(
            name='MemberLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('github', 'GitHub'), ('medium', 'Medium'), ('website', 'Personal website'), ('portfolio', 'Portfolio'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=15)),
                ('url', apps.accounts.fields.NormalizedURLField()),
                ('label', apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=120)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['link_type', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'url'), name='uniq_member_link_url')],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=200)),
                ('bio', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('location', apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=120)),
                ('province', models.CharField(blank=True, choices=[('koshi', 'Koshi'), ('madhesh', 'Madhesh'), ('bagmati', 'Bagmati'), ('gandaki', 'Gandaki'), ('lumbini', 'Lumbini'), ('karnali', 'Karnali'), ('sudurpaschim', 'Sudurpashchim'), ('outside_nepal', 'Outside Nepal')], default='', max_length=20)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=2)),
                ('experience_band', models.CharField(blank=True, default='', max_length=30)),
                ('availability', models.CharField(blank=True, choices=[('available_now', 'Available now'), ('limited', 'Limited (a few hours per week)'), ('unavailable', 'Not available')], default='', max_length=20)),
                ('interests', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('contribution_preferences', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('avatar', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.accounts.models.member_avatar_path)),
                ('field_visibility', models.JSONField(default=dict)),
                ('directory_discoverable', models.BooleanField(default=False)),
                ('leaderboard_opt_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'member profile',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['directory_discoverable'], name='idx_profile_discoverable')],
            },
        ),
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_rating', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='taxonomy.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['skill__name'],
                'indexes': [models.Index(fields=['user'], name='idx_memberskill_user')],
                'constraints': [models.UniqueConstraint(fields=('user', 'skill'), name='uniq_member_skill')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('device_label', apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'last_activity'], name='idx_usersession_user_activity')],
            },
        ),
    ]
