# Generated by Django 6.1.1 on 2026-09-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membereducation_memberlink_memberprofile_memberskill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='field_visibility',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
