# ruff: noqa: RUF012
# Generated by Django 6.1.1 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_memberprofile_field_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="github_onboarding_skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
    ]
