# Generated by Django 6.1.1 on 2026-09-03 09:32

import apps.contributions.models
import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('taxonomy', '0002_seed_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', apps.taxonomy.fields.NFCCharField(max_length=200)),
                ('description', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('evidence_url', models.URLField(blank=True, default='')),
                ('evidence_file', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.contributions.models.evidence_upload_path)),
                ('source', models.CharField(choices=[('provider_event', 'Authoritative provider event'), ('maintainer_attestation', 'Maintainer attestation'), ('member_submission', 'Member-submitted evidence')], default='member_submission', max_length=25)),
                ('provider_event_ref', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('pending_info', 'Clarification requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], db_index=True, default='candidate', max_length=15)),
                ('impact_tier', models.CharField(choices=[('minor', 'Minor'), ('standard', 'Standard'), ('major', 'Major')], default='standard', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_note', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('pending_mapping', models.BooleanField(default=False)),
                ('revocation_reason', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='taxonomy.taxonomyterm')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='projects.project')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_contributions', to=settings.AUTH_USER_MODEL)),
                ('secondary_approval_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_approvals', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified_at', '-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='idx_contrib_project_status'), models.Index(fields=['contributor', 'status'], name='idx_contrib_contributor_status'), models.Index(fields=['status', '-verified_at'], name='idx_contrib_status_verified'), models.Index(fields=['contribution_type', '-verified_at'], name='idx_contrib_type_verified')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_event_ref', ''), _negated=True), fields=('provider_event_ref',), name='uniq_contrib_provider_event_ref')],
            },
        ),
    ]
