# Generated by Django 6.1.1 on 2026-09-05

import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Persist reversible, PMO-governed holds for unscored contribution outcomes."""

    dependencies = [
        ("contributions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contributionrecord",
            name="hold_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contributionrecord",
            name="held_from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("candidate", "Candidate"),
                    ("pending_info", "Clarification requested"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("revoked", "Revoked"),
                ],
                default="",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="contributionrecord",
            name="hold_reason",
            field=apps.taxonomy.fields.NFCTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contributionrecord",
            name="held_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contributionrecord",
            name="held_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="held_contributions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contributionrecord",
            name="hold_released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contributionrecord",
            name="hold_released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="released_contribution_holds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contributionrecord",
            name="hold_release_reason",
            field=apps.taxonomy.fields.NFCTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contributionrecord",
            name="hold_response",
            field=apps.taxonomy.fields.NFCTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contributionrecord",
            name="hold_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="contributionrecord",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(("hold_active", True))
                    | (
                        models.Q(
                            ("held_at__isnull", False),
                            ("held_by__isnull", False),
                            ("held_from_status__in", ("candidate", "pending_info")),
                            ("hold_active", True),
                        )
                        & ~models.Q(("hold_reason", ""))
                    )
                ),
                name="contrib_hold_metadata_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="contributionrecord",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("hold_responded_at__isnull", True), ("hold_response", ""))
                    | (
                        models.Q(("hold_responded_at__isnull", False))
                        & ~models.Q(("hold_response", ""))
                    )
                ),
                name="contrib_hold_response_consistent",
            ),
        ),
    ]
