# Generated by Django 6.1.1 on 2026-09-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_contributionrecord_pmo_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionrecord',
            name='evidence_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contributionrecord',
            name='evidence_scan',
            field=models.CharField(choices=[('not_applicable', 'No file submitted'), ('pending', 'Pending security check'), ('clean', 'Security check passed'), ('quarantined', 'Quarantined'), ('failed', 'Security check failed')], db_index=True, default='not_applicable', max_length=14),
        ),
        migrations.AddField(
            model_name='contributionrecord',
            name='evidence_size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
