# Generated by Django 6.1.1 on 2026-09-03 09:34

import apps.taxonomy.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub')], default='github', verbose_name=10)),
                ('github_user_id', models.BigIntegerField(unique=True)),
                ('login', apps.taxonomy.fields.NFCCharField(verbose_name=100)),
                ('scopes', models.JSONField(default=list)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('consent_scopes', models.JSONField(default=list)),
                ('consent_recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('show_annual_calendar', models.BooleanField(default=False)),
                ('calendar_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub')], default='github', verbose_name=10)),
                ('installation_id', models.BigIntegerField()),
                ('repository_id', models.BigIntegerField()),
                ('repository_node_id', models.CharField(blank=True, default='', verbose_name=100)),
                ('full_name', apps.taxonomy.fields.NFCCharField(verbose_name=250)),
                ('granted_scopes', models.JSONField(default=list)),
                ('sync_state', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('degraded', 'Degraded'), ('stopped', 'Stopped'), ('error', 'Error')], db_index=True, default='idle', verbose_name=10)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_cursor', models.CharField(blank=True, default='', verbose_name=255)),
                ('health_note', apps.taxonomy.fields.NFCTextField(blank=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_repositories', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repository_connections', to='projects.project')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub')], default='github', verbose_name=10)),
                ('event_type', models.CharField(db_index=True, verbose_name=100)),
                ('delivery_id', models.CharField(verbose_name=200)),
                ('provider_event_id', models.CharField(verbose_name=200)),
                ('source', models.CharField(choices=[('webhook', 'Webhook'), ('reconciliation', 'Reconciliation')], default='webhook', verbose_name=15)),
                ('signature_valid', models.BooleanField(default=False)),
                ('signature_note', models.CharField(blank=True, default='', verbose_name=50)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('payload_digest', models.CharField(blank=True, default='', verbose_name=64)),
                ('processing_state', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('duplicate', 'Duplicate'), ('ignored', 'Ignored'), ('rejected', 'Rejected')], db_index=True, default='pending', verbose_name=12)),
                ('processing_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', verbose_name=100)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_events', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_events', to='github_sync.repositoryconnection')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='repositoryconnection',
            index=models.Index(fields=['sync_state'], name='idx_repoconn_sync_state'),
        ),
        migrations.AddIndex(
            model_name='repositoryconnection',
            index=models.Index(fields=['project'], name='idx_repoconn_project'),
        ),
        migrations.AddIndex(
            model_name='repositoryconnection',
            index=models.Index(fields=['provider', 'repository_node_id'], name='idx_repoconn_provider_node'),
        ),
        migrations.AddConstraint(
            model_name='repositoryconnection',
            constraint=models.UniqueConstraint(fields=('provider', 'repository_id'), name='uniq_repo_connection'),
        ),
        migrations.AddIndex(
            model_name='providerevent',
            index=models.Index(fields=['processing_state', 'received_at'], name='idx_provevent_state_received'),
        ),
        migrations.AddIndex(
            model_name='providerevent',
            index=models.Index(fields=['repository', 'received_at'], name='idx_provevent_repo_received'),
        ),
        migrations.AddConstraint(
            model_name='providerevent',
            constraint=models.UniqueConstraint(fields=('provider', 'delivery_id'), name='uniq_provider_delivery'),
        ),
        migrations.AddConstraint(
            model_name='providerevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='uniq_provider_event'),
        ),
    ]
