# Generated by Django 6.1.1 on 2026-09-05

import apps.taxonomy.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("github_sync", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="repositoryconnection",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repositoryconnection",
            name="task_snapshot_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repositoryconnection",
            name="task_snapshot_note",
            field=apps.taxonomy.fields.NFCTextField(blank=True),
        ),
        migrations.CreateModel(
            name="GithubStarterTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("github_issue_id", models.BigIntegerField()),
                ("number", models.PositiveIntegerField()),
                ("title", apps.taxonomy.fields.NFCCharField(verbose_name=300)),
                ("url", models.URLField()),
                ("labels", models.JSONField(default=list)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("repository", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="starter_tasks", to="github_sync.repositoryconnection")),
            ],
            options={"ordering": ["repository", "number"]},
        ),
        migrations.AddIndex(
            model_name="githubstartertask",
            index=models.Index(fields=["repository", "number"], name="idx_startertask_repo_number"),
        ),
        migrations.AddConstraint(
            model_name="githubstartertask",
            constraint=models.UniqueConstraint(fields=("repository", "github_issue_id"), name="uniq_github_starter_issue"),
        ),
    ]
