# Generated by Django 6.1.1 on 2026-09-05 13:05

import apps.taxonomy.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_sync', '0003_repository_operational_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconnection',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='bio',
            field=apps.taxonomy.fields.NFCTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='company',
            field=apps.taxonomy.fields.NFCCharField(blank=True, default='', verbose_name=255),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='display_name',
            field=apps.taxonomy.fields.NFCCharField(blank=True, default='', verbose_name=255),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='html_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='location',
            field=apps.taxonomy.fields.NFCCharField(blank=True, default='', verbose_name=255),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='public_profile_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='public_repos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositoryconnection',
            name='public_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repositoryconnection',
            name='public_snapshot_note',
            field=apps.taxonomy.fields.NFCTextField(blank=True),
        ),
        migrations.CreateModel(
            name='GithubIssueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_issue_id', models.BigIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('title', apps.taxonomy.fields.NFCCharField(verbose_name=300)),
                ('body', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('state', models.CharField(max_length=20)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('url', models.URLField()),
                ('labels', models.JSONField(default=list)),
                ('author_login', apps.taxonomy.fields.NFCCharField(blank=True, default='', verbose_name=100)),
                ('author_avatar_url', models.URLField(blank=True, default='')),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_snapshots', to='github_sync.repositoryconnection')),
            ],
            options={
                'ordering': ['repository', 'number'],
                'constraints': [models.UniqueConstraint(fields=('repository', 'github_issue_id'), name='uniq_github_issue_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='GithubPullRequestSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_pull_request_id', models.BigIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('title', apps.taxonomy.fields.NFCCharField(verbose_name=300)),
                ('body', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('state', models.CharField(max_length=20)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('url', models.URLField()),
                ('author_login', apps.taxonomy.fields.NFCCharField(blank=True, default='', verbose_name=100)),
                ('author_avatar_url', models.URLField(blank=True, default='')),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_request_snapshots', to='github_sync.repositoryconnection')),
            ],
            options={
                'ordering': ['repository', 'number'],
                'constraints': [models.UniqueConstraint(fields=('repository', 'github_pull_request_id'), name='uniq_github_pr_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='GithubRepositoryContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField()),
                ('login', apps.taxonomy.fields.NFCCharField(verbose_name=100)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('profile_url', models.URLField(blank=True, default='')),
                ('contributions', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_snapshots', to='github_sync.repositoryconnection')),
            ],
            options={
                'ordering': ['repository', '-contributions', 'login'],
                'constraints': [models.UniqueConstraint(fields=('repository', 'github_user_id'), name='uniq_github_repo_contributor')],
            },
        ),
    ]
