# Generated by Django 6.1.1 on 2026-09-05 13:44

import apps.taxonomy.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_sync', '0004_githubconnection_avatar_url_githubconnection_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubPublicProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField(unique=True)),
                ('login', apps.taxonomy.fields.NFCCharField(db_index=True, verbose_name=100)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('html_url', models.URLField()),
                ('display_name', apps.taxonomy.fields.NFCCharField(blank=True, default='', verbose_name=255)),
                ('bio', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('location', apps.taxonomy.fields.NFCCharField(blank=True, default='', verbose_name=255)),
                ('company', apps.taxonomy.fields.NFCCharField(blank=True, default='', verbose_name=255)),
                ('public_repos', models.PositiveIntegerField(default=0)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['login'],
            },
        ),
    ]
