# Generated by Django 6.1.1 on 2026-09-03 08:34

import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', apps.taxonomy.fields.NFCCharField(max_length=200)),
                ('name_ne', apps.taxonomy.fields.NFCTextField(blank=True)),
                ('slug', apps.taxonomy.fields.NFCSlugField(allow_unicode=True, max_length=220, unique=True)),
                ('abbreviation', apps.taxonomy.fields.NFCCharField(blank=True, max_length=20)),
                ('description', apps.taxonomy.fields.NFCTextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending activation'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='pending', max_length=12)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', apps.taxonomy.fields.NFCTextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', apps.taxonomy.fields.NFCTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provisioned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_ministries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ministry organization',
                'ordering': ['name_en', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MinistryPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', apps.taxonomy.fields.NFCCharField(max_length=120)),
                ('official_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_publisher_roles', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='ministries.ministryorganization')),
                ('revoked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_publisher_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ministry__name_en', 'user__username'],
            },
        ),
        migrations.AddIndex(
            model_name='ministryorganization',
            index=models.Index(fields=['status'], name='idx_ministry_status'),
        ),
        migrations.AddIndex(
            model_name='ministrypublisher',
            index=models.Index(fields=['user', 'status'], name='idx_publisher_user_status'),
        ),
        migrations.AddIndex(
            model_name='ministrypublisher',
            index=models.Index(fields=['ministry', 'status'], name='idx_publisher_ministry_status'),
        ),
        migrations.AddConstraint(
            model_name='ministrypublisher',
            constraint=models.UniqueConstraint(fields=('user', 'ministry'), name='uniq_publisher_user_ministry'),
        ),
    ]
