# Generated by Django 6.1.1 on 2026-09-03 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ministrypublisher',
            name='uniq_publisher_user_ministry',
        ),
        migrations.AddConstraint(
            model_name='ministrypublisher',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'ministry'), name='uniq_active_publisher_user_ministry'),
        ),
    ]
