# Generated by Django 6.1.1 on 2026-09-03 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0002_remove_ministrypublisher_uniq_publisher_user_ministry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministrypublisher',
            name='contact_verification_status',
            field=models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='ministrypublisher',
            name='contact_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OfficialContactChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='pending', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_challenges', to='ministries.ministrypublisher')),
            ],
            options={
                'verbose_name': 'official contact challenge',
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['publisher', 'status'], name='idx_contact_challenge_state'), models.Index(fields=['expires_at'], name='idx_contact_challenge_expiry')],
            },
        ),
    ]
