# Generated by Django 6.1.1 on 2026-09-05 10:39

import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0003_ministrypublisher_contact_verification_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryOnboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('name_en', apps.taxonomy.fields.NFCCharField(max_length=200)),
                ('name_ne', apps.taxonomy.fields.NFCTextField(blank=True)),
                ('abbreviation', apps.taxonomy.fields.NFCCharField(blank=True, max_length=20)),
                ('website_url', models.URLField()),
                ('official_email', models.EmailField(max_length=254)),
                ('nominated_officer_name', apps.taxonomy.fields.NFCCharField(max_length=160)),
                ('nominated_officer_title', apps.taxonomy.fields.NFCCharField(max_length=160)),
                ('purpose', apps.taxonomy.fields.NFCTextField()),
                ('focal_contact', apps.taxonomy.fields.NFCCharField(max_length=160)),
                ('nomination_reference', apps.taxonomy.fields.NFCCharField(max_length=180)),
                ('signatory_name', apps.taxonomy.fields.NFCCharField(max_length=160)),
                ('domain_verified', models.BooleanField(default=False)),
                ('named_person_verified', models.BooleanField(default=False)),
                ('signatory_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New request'), ('provisioned', 'Provisioned'), ('declined', 'Declined')], default='new', max_length=16)),
                ('decline_reason', apps.taxonomy.fields.NFCTextField(blank=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_ministry_onboarding_requests', to=settings.AUTH_USER_MODEL)),
                ('provisioned_organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_request', to='ministries.ministryorganization')),
            ],
            options={
                'verbose_name': 'ministry onboarding request',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_onboarding_request_state')],
            },
        ),
    ]
