# Generated by Django 6.1.1 on 2026-09-03 09:23

import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('impersonation', 'Impersonation'), ('gov_branding_misuse', 'Misleading government branding'), ('unsafe_link', 'Unsafe link'), ('malware', 'Malicious file'), ('copyright', 'Copyright or intellectual property'), ('harassment', 'Harassment or code-of-conduct violation'), ('spam', 'Spam'), ('unlawful_content', 'Unlawful content'), ('security_concern', 'Security concern'), ('other', 'Other')], db_index=True, max_length=25)),
                ('details', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('evidence_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_reports', to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('action_taken', 'Action taken'), ('closed_no_action', 'Closed - no action'), ('appealed', 'Appealed'), ('escalated', 'Escalated')], db_index=True, default='new', max_length=16)),
                ('action', models.CharField(blank=True, default='', max_length=25)),
                ('action_reason', models.CharField(blank=True, default='', max_length=25)),
                ('decision_comment', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_text', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('appealed_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_status', models.CharField(blank=True, default='', max_length=10)),
                ('appeal_decided_at', models.DateTimeField(blank=True, null=True)),
                ('security_containment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appeal_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_decisions', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_cases', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='moderation.report')),
            ],
            options={
                'verbose_name': 'moderation case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('commented', 'Comment'), ('action_taken', 'Action taken'), ('appealed', 'Appealed'), ('escalated', 'Escalated'), ('decided', 'Decided'), ('reinstated', 'Reinstated')], max_length=15)),
                ('comment', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='moderation.moderationcase')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['case', 'created_at'], name='idx_caseevent_case_created')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_report_target'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reason', 'created_at'], name='idx_report_reason_created'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['status', '-created_at'], name='idx_case_status_created'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['assigned_to', 'status'], name='idx_case_assignee_status'),
        ),
    ]
