# Generated by Django 6.1.1 on 2026-09-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationcase',
            name='enforcement_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
