#!/usr/bin/env python3
"""Split prototype/index.html — the design-canvas bundle — into per-screen
reference HTML, the Industry token CSS, and a route table.

The bundle is a self-extracting page: one JSON line holds a manifest of
assets, another holds the canvas document as a single JSON string. We never
execute it; we read the string and cut it at each board's
`data-screen-label`. The canvas runtime is not needed to display a board —
each one is plain HTML styled by CSS custom properties.

Outputs (all under frontend/src/, all generated, all committed so the app
builds without Python):

  tokens/industry.css      the canvas's design system, @font-face removed
                           (fonts come from Google Fonts in the app)
  screens/ref/<id>.html    one file per board: its <main> only — the board's
                           own <nav> and <aside> are chrome the app shell
                           replaces. Boards without a <main> keep everything.
  routes.json              [{id, label, actor, job, path, tier, story}]
                           tier is "ref" for every screen this script writes;
                           a live component claims a route by flipping it.

Run from frontend/:  python3 scripts/extract-canvas.py
"""
from __future__ import annotations

import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]          # frontend/
SRC = ROOT.parent / "prototype" / "index.html"
OUT_REF = ROOT / "src" / "screens" / "ref"
OUT_CSS = ROOT / "src" / "tokens" / "industry.css"
OUT_ROUTES = ROOT / "src" / "routes.json"

ACTOR = {"a": "public", "b": "member", "c": "publisher", "d": "admin"}

# Screen id → app route. Anything not listed falls back to /<id>, which is
# stable and shareable but says nothing; give the demo-visible ones real paths.
PATHS = {
    "a1-1": "/",
    "a1-2": "/how-to-contribute",
    "a1-3": "/projects/public-example",
    "a2-1": "/projects",
    "a2-2": "/projects/:slug",
    "a2-3": "/sign-in",
    "a3-1": "/blogs",
    "a3-2": "/blogs/:slug",
    "a3-3": "/members",
    "a3-4": "/members/:username",
    "a3-5": "/community",
    "a3-6": "/recognition",
    "a3-7": "/recognition/badges",
    "b2-3": "/projects/:slug/apply",
    "b2-4": "/me/applications/:id/accepted",
    "b2-6": "/me/applications/:id/evidence",
    "b2-8": "/me/applications/:id/recognised",
    "b5-5": "/me",
    "b6-5": "/me/applications/:id",
    "c3-1": "/ministry",
    "c3-2": "/ministry/applications/:id",
    "c4-1": "/ministry/verification",
    "c4-2": "/ministry/verification/:id",
    "d5-1": "/admin",
}


def load_canvas(bundle: pathlib.Path) -> str:
    for line in bundle.read_text(encoding="utf-8").split("\n"):
        s = line.strip().rstrip(",")
        if s.startswith('"<!DOCTYPE') or s.startswith('"\\u003c!DOCTYPE'):
            return json.loads(s)
    sys.exit("canvas document not found in bundle")


def clean(fragment: str) -> str:
    # The canvas runtime spells SVG's viewBox as a custom attribute so the
    # HTML parser keeps its case; restore it or every icon renders at 0×0.
    fragment = fragment.replace("sc-camel-view-box=", "viewBox=")
    return fragment.strip() + "\n"


def story_text(raw: str) -> str:
    text = html.unescape(re.sub(r"<[^>]+>", " ", raw))
    return re.sub(r"\s+", " ", text).strip()


def main() -> None:
    canvas = load_canvas(SRC)

    css = re.search(r"<style>(.*?)</style>", canvas, re.S).group(1)
    css = re.sub(r"@font-face\s*\{[^}]*\}\s*", "", css)
    OUT_CSS.parent.mkdir(parents=True, exist_ok=True)
    OUT_CSS.write_text(
        "/* GENERATED by scripts/extract-canvas.py from prototype/index.html — do not edit.\n"
        "   The canvas's own design system (\"Industry\"). Its tokens are re-pointed at the\n"
        "   Nepal palette in industry-aliases.css, which loads AFTER this file. */\n" + css.strip() + "\n"
    )

    marker = re.compile(r'<div id="([a-d]\d+-\d+)"\s+data-screen-label="([^"]*)"')
    boards = list(marker.finditer(canvas))
    if not boards:
        sys.exit("no boards found — has the canvas format changed?")

    OUT_REF.mkdir(parents=True, exist_ok=True)
    for stale in OUT_REF.glob("*.html"):
        stale.unlink()

    routes = []
    for i, m in enumerate(boards):
        end = boards[i + 1].start() if i + 1 < len(boards) else len(canvas)
        board = canvas[m.start():end]

        # The narrative that precedes the board on the canvas describes the job.
        # It is the LAST story block before the board, and it contains nested
        # <sc-if> toggles, so a non-greedy match stops at the wrong closer.
        # Anchor on the last opener and take everything to the window's end.
        before = canvas[max(0, m.start() - 6000):m.start()]
        story_m = re.search(
            r'<sc-if value="\{\{ story \}\}"[^>]*>(?!.*<sc-if value="\{\{ story \}\}")(.*)</sc-if>\s*$',
            before,
            re.S,
        )
        story = story_text(story_m.group(1)) if story_m else ""

        main_el = re.search(r"<main\b.*?</main>", board, re.S)
        if main_el:
            fragment = main_el.group(0)
        else:
            # Public pages have no <main>: their own top nav and footer are
            # inside the board. Those are chrome the app shell provides, so
            # strip them; <aside> stays — on these boards it is content (the
            # catalog's filter column, a project's sidebar), not a rail.
            fragment = re.sub(r'<nav class="nav".*?</nav>', "", board, count=1, flags=re.S)
            fragment = re.sub(r"<footer\b.*?</footer>", "", fragment, flags=re.S)
        (OUT_REF / f"{m.group(1)}.html").write_text(clean(fragment), encoding="utf-8")

        sid, label = m.group(1), m.group(2)
        code, _, title = label.partition(" ")
        routes.append({
            "id": sid,
            "code": code,                       # "B2.3"
            "label": title,                     # "Apply to a workstream"
            "actor": ACTOR[sid[0]],
            "job": code.split(".")[0],          # "B2"
            "path": PATHS.get(sid, f"/{sid}"),
            "tier": "ref",
            "hasMain": bool(main_el),
            "story": story,
        })

    OUT_ROUTES.write_text(json.dumps(routes, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")

    with_main = sum(r["hasMain"] for r in routes)
    print(f"{len(routes)} screens → {OUT_REF.relative_to(ROOT)}  ({with_main} with <main>, "
          f"{len(routes) - with_main} kept whole)")
    print(f"industry.css {OUT_CSS.stat().st_size:,} bytes → {OUT_CSS.relative_to(ROOT)}")
    print(f"routes.json  {len(routes)} routes → {OUT_ROUTES.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
