# Generated by Django 6.1.1 on 2026-09-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrun',
            name='error_code',
            field=models.CharField(blank=True, choices=[('command_error', 'Command error'), ('connection_error', 'Connection error'), ('database_error', 'Database error'), ('timeout', 'Timeout'), ('unexpected_error', 'Unexpected error')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
