# Generated by Django 6.1.1 on 2026-09-03 09:21

import apps.accounts.fields
import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0002_seed_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', apps.taxonomy.fields.NFCCharField(verbose_name=200)),
                ('excerpt', apps.taxonomy.fields.NFCTextField(blank=True)),
                ('canonical_url', apps.accounts.fields.NormalizedURLField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', verbose_name=2)),
                ('reading_time_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('archived', 'Archived')], db_index=True, default='draft', verbose_name=12)),
                ('moderation_state', models.CharField(choices=[('not_reviewed', 'Not reviewed'), ('under_review', 'Under review'), ('restricted', 'Restricted'), ('reinstated', 'Reinstated')], default='not_reviewed', verbose_name=15)),
                ('is_official', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('official_published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_posts', to='taxonomy.taxonomyterm')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_versions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='blogs.blogpost')),
            ],
            options={
                'ordering': ['post', '-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-published_at'], name='idx_blog_status_published'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author', '-published_at'], name='idx_blog_author_published'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['language', 'status'], name='idx_blog_language_status'),
        ),
        migrations.AddIndex(
            model_name='blogversion',
            index=models.Index(fields=['post', '-created_at'], name='idx_blogversion_post_created'),
        ),
        migrations.AddConstraint(
            model_name='blogversion',
            constraint=models.UniqueConstraint(fields=('post', 'version_number'), name='uniq_blog_version_number'),
        ),
    ]
