# Generated by Django 6.1.1 on 2026-09-05 07:47

import apps.accounts.fields
import apps.taxonomy.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_markdown',
            field=apps.taxonomy.fields.NFCTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_rendered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_alt',
            field=apps.taxonomy.fields.NFCCharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_url',
            field=apps.accounts.fields.NormalizedURLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(choices=[('native', 'DevNepal post'), ('external', 'External article')], db_index=True, default='external', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='canonical_url',
            field=apps.accounts.fields.NormalizedURLField(blank=True),
        ),
    ]
