# Generated by Django 6.1.1 on 2026-09-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_content_markdown_blogpost_content_rendered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
