# Generated by Django 6.1.1 on 2026-09-05 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogpost_content_rendered'),
        ('projects', '0003_communitytermsacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='official_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_blog_posts', to='projects.project'),
        ),
    ]
