# Generated by Django 6.1.1 on 2026-09-05 09:18

from django.db import migrations, models


def clear_legacy_official_provenance(apps, schema_editor):
    BlogPost = apps.get_model("blogs", "BlogPost")
    AuditEvent = apps.get_model("audit", "AuditEvent")
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_type, _ = ContentType.objects.get_or_create(
        app_label="blogs",
        model="blogpost",
    )
    legacy_posts = BlogPost.objects.filter(is_official=True).filter(
        models.Q(official_published_by__isnull=True)
        | models.Q(official_project__isnull=True)
    )
    for post in legacy_posts.iterator():
        before = {
            "is_official": post.is_official,
            "official_published_by_id": post.official_published_by_id,
            "official_project_id": post.official_project_id,
        }
        post.is_official = False
        post.official_published_by_id = None
        post.official_project_id = None
        post.save(
            update_fields=["is_official", "official_published_by", "official_project"]
        )
        AuditEvent.objects.create(
            actor_id=None,
            action="blog.official.legacy_provenance_cleared",
            content_type=content_type,
            object_id=str(post.pk),
            before=before,
            after={
                "is_official": False,
                "official_published_by_id": None,
                "official_project_id": None,
            },
            source="migration",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogpost_official_project'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_legacy_official_provenance, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.CheckConstraint(condition=models.Q(('is_official', False), models.Q(('official_published_by__isnull', False), ('official_project__isnull', False)), _connector='OR'), name='chk_official_blog_provenance'),
        ),
    ]
