# Generated by Django 6.1.1 on 2026-09-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogpost_chk_official_blog_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='external_rights_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
