# Generated by Django 6.1.1 on 2026-09-03 11:36

import apps.recognition.models
import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', apps.taxonomy.fields.NFCCharField(max_length=100, unique=True)),
                ('slug', apps.taxonomy.fields.NFCSlugField(allow_unicode=True, max_length=120, unique=True)),
                ('description', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('criteria_md', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('criteria_version', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('contribution', 'Contribution'), ('milestone', 'Milestone'), ('community', 'Community'), ('special', 'Special')], default='contribution', max_length=12)),
                ('icon', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.recognition.models.badge_icon_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoringPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('rules', models.JSONField(default=dict)),
                ('document_url', models.URLField(blank=True, default='')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scoring_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scoring policy',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ContributionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='contributions.contributionrecord')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='recognition.scoringpolicy')),
            ],
            options={
                'ordering': ['-scored_at'],
            },
        ),
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=8)),
                ('revocation_reason', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='recognition.badge')),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_awards', to='contributions.contributionrecord')),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_badge_awards', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='badge_awards', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_badge_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='idx_award_recipient_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('badge', 'recipient'), name='uniq_active_award_badge_recipient')],
            },
        ),
        migrations.AddConstraint(
            model_name='scoringpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_active_scoring_policy'),
        ),
        migrations.AddIndex(
            model_name='contributionscore',
            index=models.Index(fields=['policy', '-points'], name='idx_score_policy_points'),
        ),
    ]
