# Generated by Django 6.1.1 on 2026-09-05 10:44

import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_evidence_file_security'),
        ('recognition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('consolidate', 'Consolidate'), ('release_held', 'Release held'), ('invalidate', 'Invalidate'), ('adjust_score', 'Adjust score')], max_length=16)),
                ('reason', apps.taxonomy.fields.NFCCharField(choices=[('duplicate_trivial_batch', 'Batch of trivial changes'), ('evidence_reassessment', 'Evidence reassessment'), ('maintainer_correction', 'Maintainer correction'), ('invalid_source', 'Invalid or duplicate source'), ('score_calculation_error', 'Score calculation error'), ('hold_resolved', 'Outcome hold resolved')], max_length=80)),
                ('basis', apps.taxonomy.fields.NFCTextField()),
                ('member_note', apps.taxonomy.fields.NFCTextField()),
                ('adjusted_points', models.PositiveIntegerField(blank=True, null=True)),
                ('before_snapshot', models.JSONField(default=dict)),
                ('after_snapshot', models.JSONField(default=dict)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('appeal_due_at', models.DateTimeField()),
                ('appeal_text', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('appealed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('appealed', 'Appealed'), ('upheld', 'Upheld'), ('overturned', 'Overturned')], db_index=True, default='applied', max_length=10)),
                ('appeal_decided_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_decision_reason', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('appeal_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_recognition_correction_appeals', to=settings.AUTH_USER_MODEL)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_recognition_corrections', to=settings.AUTH_USER_MODEL)),
                ('contributions', models.ManyToManyField(related_name='recognition_corrections', to='contributions.contributionrecord')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognition_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['recipient', '-applied_at'], name='idx_correction_recipient'), models.Index(fields=['status', 'appeal_due_at'], name='idx_correction_appeal')],
            },
        ),
    ]
