# Generated by Django 6.1.1 on 2026-09-05 10:05

import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='affects_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='owner',
            field=apps.taxonomy.fields.NFCCharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='reason',
            field=apps.taxonomy.fields.NFCTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='scope',
            field=apps.taxonomy.fields.NFCCharField(default='Everyone', max_length=120),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FeatureFlagChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('from_enabled', models.BooleanField()),
                ('to_enabled', models.BooleanField()),
                ('reason', apps.taxonomy.fields.NFCTextField()),
                ('status', models.CharField(choices=[('pending', 'Awaiting a second Super Admin'), ('applied', 'Applied'), ('withdrawn', 'Withdrawn')], default='pending', max_length=12)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_flag_changes', to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='administration.featureflag')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_flag_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feature flag change',
                'verbose_name_plural': 'feature flag changes',
                'ordering': ['-proposed_at', '-id'],
                'indexes': [models.Index(fields=['status', 'proposed_at'], name='idx_flagchange_status')],
                'constraints': [models.UniqueConstraint(fields=('flag', 'version'), name='uniq_flagchange_version')],
            },
        ),
    ]
