# Generated by Django 6.1.1 on 2026-09-05 10:12

import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_featureflag_affects_members_featureflag_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('grant', 'Grant Super Admin'), ('revoke', 'Revoke Super Admin')], max_length=8)),
                ('reason', apps.taxonomy.fields.NFCTextField()),
                ('status', models.CharField(choices=[('pending', 'Awaiting a second Super Admin'), ('applied', 'Applied'), ('withdrawn', 'Withdrawn')], default='pending', max_length=12)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_super_admin_grants', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_super_admin_grants', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='super_admin_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'super admin grant',
                'verbose_name_plural': 'super admin grants',
                'ordering': ['-proposed_at', '-id'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='idx_grant_status_expiry')],
            },
        ),
    ]
