# Generated by Django 6.1.1 on 2026-09-05 07:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '0003_ministrypublisher_contact_verification_status_and_more'),
        ('projects', '0003_communitytermsacceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_name', models.CharField(choices=[('project_viewed', 'Project viewed'), ('project_applied', 'Project application submitted'), ('contribution_accepted', 'Contribution accepted')], db_index=True, max_length=32)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('source_ref', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_events', to='ministries.ministryorganization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_events', to='projects.project')),
            ],
            options={
                'verbose_name': 'analytics event',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['ministry', 'occurred_at'], name='idx_analytics_ministry_month'), models.Index(fields=['project', 'occurred_at'], name='idx_analytics_project_month')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_ref__gt', '')), fields=('source_ref',), name='uniq_analytics_source_ref')],
            },
        ),
    ]
