# Generated by Django 6.1.1 on 2026-09-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('ministries', '0003_ministrypublisher_contact_verification_status_and_more'),
        ('projects', '0003_communitytermsacceptance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analyticseventrecord',
            constraint=models.CheckConstraint(condition=models.Q(('event_name__in', ['project_viewed', 'project_applied', 'contribution_accepted'])), name='analytics_event_name_documented'),
        ),
    ]
