# Generated by Django 6.1.1 on 2026-09-03 08:22

import apps.taxonomy.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spdx_id', models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9.+-]+$')], verbose_name=80)),
                ('name', apps.taxonomy.fields.NFCCharField(verbose_name=200)),
                ('reference_url', models.URLField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'approved license',
                'ordering': ['spdx_id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', apps.taxonomy.fields.NFCCharField(verbose_name=100)),
                ('slug', apps.taxonomy.fields.NFCSlugField(allow_unicode=True, unique=True, verbose_name=120)),
                ('description', apps.taxonomy.fields.NFCTextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='idx_skill_active')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_skill_name')],
            },
        ),
        migrations.CreateModel(
            name='SkillSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', apps.taxonomy.fields.NFCCharField(verbose_name=100)),
                ('note', apps.taxonomy.fields.NFCTextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', verbose_name=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_suggestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('term_name',), name='uniq_suggestion_term')],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.CharField(choices=[('project_category', 'Project category'), ('contribution_type', 'Contribution type'), ('technology', 'Technology'), ('experience_band', 'Experience band'), ('tag', 'Tag')], db_index=True, verbose_name=30)),
                ('label', apps.taxonomy.fields.NFCCharField(verbose_name=150)),
                ('slug', apps.taxonomy.fields.NFCSlugField(allow_unicode=True, verbose_name=170)),
                ('description', apps.taxonomy.fields.NFCTextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='taxonomy.taxonomyterm')),
            ],
            options={
                'ordering': ['vocabulary', 'sort_order', 'label'],
                'indexes': [models.Index(fields=['vocabulary', 'is_active'], name='idx_term_vocab_active')],
                'constraints': [models.UniqueConstraint(fields=('vocabulary', 'slug'), name='uniq_term_vocab_slug'), models.UniqueConstraint(fields=('vocabulary', 'label'), name='uniq_term_vocab_label')],
            },
        ),
    ]
