# Generated by Django 6.1.1 on 2026-09-03 18:26

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_seed_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='skillsuggestion',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('term_name'), name='uniq_suggestion_term_ci'),
        ),
    ]
