# Generated by Django 6.1.1 on 2026-09-05 10:45

import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_skillsuggestion_uniq_suggestion_term_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedlicense',
            name='legal_approved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvedlicense',
            name='legal_reference',
            field=apps.taxonomy.fields.NFCCharField(blank=True, default='', verbose_name=60),
        ),
        migrations.AddField(
            model_name='approvedlicense',
            name='use',
            field=models.CharField(choices=[('code', 'Code'), ('content_data', 'Content and data')], default='code', max_length=16),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ne',
            field=apps.taxonomy.fields.NFCCharField(blank=True, default='', verbose_name=100),
        ),
        migrations.CreateModel(
            name='TaxonomyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('action', models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deprecated', 'Deprecated'), ('reinstated', 'Reinstated'), ('merged', 'Merged')], max_length=12)),
                ('subject_label', apps.taxonomy.fields.NFCCharField(verbose_name=150)),
                ('summary', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxonomy_versions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='taxonomy.skill')),
            ],
            options={
                'verbose_name': 'taxonomy version',
                'verbose_name_plural': 'taxonomy versions',
                'ordering': ['-version'],
            },
        ),
    ]
