# Generated by Django 6.1.1 on 2026-09-03 09:21

import apps.taxonomy.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_applications', models.BooleanField(default=True)),
                ('email_reviews', models.BooleanField(default=True)),
                ('email_contributions', models.BooleanField(default=True)),
                ('email_community', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('none', 'No digest'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('application_status', 'Application status'), ('review_decision', 'Review decision'), ('review_comment', 'Review comment'), ('assignment', 'Work assignment'), ('contribution_verified', 'Contribution verified'), ('contribution_revoked', 'Contribution revoked'), ('badge_awarded', 'Badge awarded'), ('project_update', 'Project update'), ('project_status', 'Project status change'), ('bookmark_change', 'Bookmarked project changed'), ('moderation', 'Moderation'), ('security', 'Security'), ('account', 'Account')], db_index=True, max_length=25)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email')], default='in_app', max_length=8)),
                ('title', apps.taxonomy.fields.NFCCharField(max_length=200)),
                ('body', apps.taxonomy.fields.NFCTextField(blank=True, default='')),
                ('context_url', models.CharField(blank=True, default='', max_length=500)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], db_index=True, default='pending', max_length=10)),
                ('template_version', models.CharField(blank=True, default='', max_length=20)),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_class', models.CharField(blank=True, default='', max_length=100)),
                ('dedup_key', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='idx_notif_recipient_read'), models.Index(fields=['delivery_status'], name='idx_notif_delivery_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedup_key', ''), _negated=True), fields=('recipient', 'dedup_key'), name='uniq_notif_recipient_dedup')],
            },
        ),
    ]
